// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STIVE_API.Helpers;

#nullable disable

namespace STIVE_API.Migrations
{
    [DbContext(typeof(STIVE_Context))]
    [Migration("20230104152110_CreateTableEtatCommande")]
    partial class CreateTableEtatCommande
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("STIVE_API.Models.Article", b =>
                {
                    b.Property<int>("IdArticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnneeArticle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptifArticle")
                        .HasColumnType("longtext");

                    b.Property<int>("IdDomaine")
                        .HasColumnType("int");

                    b.Property<int>("IdFamille")
                        .HasColumnType("int");

                    b.Property<int>("IdTVA")
                        .HasColumnType("int");

                    b.Property<string>("ImageArticle")
                        .HasColumnType("longtext");

                    b.Property<int?>("NbDansCartonArticle")
                        .HasColumnType("int");

                    b.Property<string>("NomArticle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PrixAchathtArticle")
                        .HasColumnType("double");

                    b.Property<double?>("PrixVenteCartonhtArticle")
                        .HasColumnType("double");

                    b.Property<double>("PrixVentehtArticle")
                        .HasColumnType("double");

                    b.Property<int?>("QuantiteEnStock")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<double?>("RistourneCartonArticle")
                        .HasColumnType("double");

                    b.HasKey("IdArticle");

                    b.ToTable("articles");
                });

            modelBuilder.Entity("STIVE_API.Models.CommandeClient", b =>
                {
                    b.Property<int>("IdCommandeClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DateCommandeClient")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EtatCommandeClient")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.HasKey("IdCommandeClient");

                    b.ToTable("commandeClients");
                });

            modelBuilder.Entity("STIVE_API.Models.CommandeDomaine", b =>
                {
                    b.Property<int>("IdCommandeDomaine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DateCommandeDomaine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EtatCommandeDomaine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdDomaine")
                        .HasColumnType("int");

                    b.HasKey("IdCommandeDomaine");

                    b.ToTable("commandeDomaines");
                });

            modelBuilder.Entity("STIVE_API.Models.Domaine", b =>
                {
                    b.Property<int>("IdDomaine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresseDomaine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodePostalDomaine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptifDomaine")
                        .HasColumnType("longtext");

                    b.Property<string>("MailDomaine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomDomaine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelephoneDomaine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VilleDomaine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdDomaine");

                    b.ToTable("domaines");
                });

            modelBuilder.Entity("STIVE_API.Models.Famille", b =>
                {
                    b.Property<int>("IdFamille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LibelleFamille")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdFamille");

                    b.ToTable("familles");
                });

            modelBuilder.Entity("STIVE_API.Models.Fonction", b =>
                {
                    b.Property<int>("IdFonction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LibelleFonction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdFonction");

                    b.ToTable("fonctions");
                });

            modelBuilder.Entity("STIVE_API.Models.LigneCommandeClient", b =>
                {
                    b.Property<int>("IdLigneCommandeClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int");

                    b.Property<int>("IdCommandeClient")
                        .HasColumnType("int");

                    b.Property<int>("QuantiteLigneCommandeClient")
                        .HasColumnType("int");

                    b.HasKey("IdLigneCommandeClient");

                    b.ToTable("ligneCommandeClients");
                });

            modelBuilder.Entity("STIVE_API.Models.LigneCommandeDomaine", b =>
                {
                    b.Property<int>("IdLigneCommandeDomaine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdArticle")
                        .HasColumnType("int");

                    b.Property<int>("IdCommandeDomaine")
                        .HasColumnType("int");

                    b.Property<int>("QuantiteLigneCommandeDomaine")
                        .HasColumnType("int");

                    b.HasKey("IdLigneCommandeDomaine");

                    b.ToTable("ligneCommandeDomaines");
                });

            modelBuilder.Entity("STIVE_API.Models.Tva", b =>
                {
                    b.Property<int>("IdTva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LibelleTVA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("TauxTva")
                        .HasColumnType("double");

                    b.HasKey("IdTva");

                    b.ToTable("tvas");
                });

            modelBuilder.Entity("STIVE_API.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresseUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodePostalUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdFonction")
                        .HasColumnType("int");

                    b.Property<string>("MailUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotdePasseUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrenomUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelephoneUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VilleUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
